name: onboard_animation
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ^3.27.2

dependencies:
  auto_size_text: ^3.0.0
  collection: null
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  grayscale: ^0.0.5+7
  hooks_riverpod: ^2.6.1
  material_color_utilities: ^0.11.0
  nested: null
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  nilts: ^0.17.0
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
