include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:

analyzer:
  plugins:
    # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gform.dart"
    - "**/firebase_options*.dart"
    - "*/.github/workflows/flutter_*.yaml"
    - "*/functions/*.js"
  errors:
    todo: ignore
    hack: ignore
    # https://pub.dev/packages/freezed#install
    invalid_annotation_target: ignore
