name: max_height_bottom_sheet_app
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  nilts: ^0.17.0
  pedantic_mono: ^1.29.0

flutter:
  uses-material-design: true
