name: linked_scroll_app
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: 0.2.0

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0

flutter:
  uses-material-design: true
