// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdV-R5_dvDhqCHg5jluLJZ6khGHerxeo',
    appId: '1:899934807737:android:552d8840da442e0415dd68',
    messagingSenderId: '899934807737',
    projectId: 'yakuran-playground',
    storageBucket: 'yakuran-playground.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGWVebgHHxXIGe_fMjb8I47jTtflLVlo',
    appId: '1:899934807737:ios:90a11edb2340d4e915dd68',
    messagingSenderId: '899934807737',
    projectId: 'yakuran-playground',
    storageBucket: 'yakuran-playground.firebasestorage.app',
    androidClientId: '899934807737-v5col7di0a4hngfeg7u8b2og1mcn9dis.apps.googleusercontent.com',
    iosClientId: '899934807737-ool5erp6kdc2tismpma5e6qb10scu1s0.apps.googleusercontent.com',
    iosBundleId: 'com.yakuran.fcmExample',
  );

}