name: {{app_name.snakeCase()}}
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  collection:
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  nested:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  nilts:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:
